/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "nfs.h"
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>

void nfs_1(char *operacja)
{
    int *result_3;
	int *result_4;
	int wyslane = 0;
	int plik_edycja;
	int koniec_1_arg;
    char linia[1024];
	char edycja[1024];
	char bufor[65536];
	char polecenie[2048];
	CLIENT *clnt;
	zwroc  *result_2;
	pliczek  *result_1;
	wyslij  push_1_arg;
	polacz  start_1_arg;
	pobieranie  pull_1_arg;

	#ifndef	DEBUG
	clnt = clnt_create (operacja, NFS, NFS_1, "udp");
	if (clnt == NULL)
    {
		clnt_pcreateerror (operacja);
		exit(-1);
	}
	#endif	/* DEBUG */

	printf("Polecenie: ");
	scanf("%s", linia);

	if(strcmp(linia,"close") == 0)   /* Zakonczenie programu */
    {
		printf("Dziekuje za uzycie uslugi NFS\n");
		exit(0);
	}
	else if(strcmp(linia,"clear") == 0)  /* Wyczyszczenie terminala */
    {
		system("clear");
		printf("Dostepne polecenia: 'read' 'open' 'upload' 'download' 'clear' 'close'\n");
		return;
	}
    else
    {
		printf("Prosze podac nazwe pliku: ");
        scanf("%s", nazwa_pliku);
	}

	if(strcmp(linia,"read") == 0)   /* Odczytanie zawartosci pliku */
    {
		strcpy(start_1_arg.nazwa, "/nfs/");
		strcpy(start_1_arg.nazwa+5, nazwa_pliku);
		start_1_arg.tryb = 2;
		result_1 = start_1(&start_1_arg, clnt);
		if (result_1 == (pliczek *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		if(result_1->plik < 0)
        {
			printf("ERROR: Blad otwarcia pliku!\n");
			return;
		}
		pull_1_arg.plik = result_1->plik;
		pull_1_arg.pozycja = 0;
		pull_1_arg.przesun = 0;
		while(1)
        {
			result_2 = pull_1(&pull_1_arg, clnt);
			if(result_2 == (zwroc *) NULL)
			{
				clnt_perror (clnt, "call failed");
			}
			if(result_2->ilosc == -1)
			{
				printf("ERROR: Blad pobierania lub przesuniecia!\n");
				koniec_1_arg = result_1->plik;
				result_4 = koniec_1(&koniec_1_arg, clnt);
				if (result_4 == (int *) NULL)
				{
					clnt_perror (clnt, "call failed");
				}
				exit(-1);
			}
			strcpy(bufor + wyslane, result_2->dane);
			wyslane = wyslane + result_2->ilosc;
			if(result_2->ilosc < 2048)
            {
                break;
            }
		}
		if(wyslane != 0)
		{
			bufor[wyslane - 1] = '\0';
			printf("Zawartosc pliku:\n%s\n", bufor);
		}
        else
		{
			bufor[0] = '\0';
			printf("*Plik jest pusty*\n");
		}
		koniec_1_arg = result_1->plik;
		result_4 = koniec_1(&koniec_1_arg, clnt);
		if (result_4 == (int *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
	}

	if(strcmp(linia,"open") == 0)   /* Edytowanie pliku */
    {
		strcpy(start_1_arg.nazwa, "/nfs/");
		strcpy(start_1_arg.nazwa+5, nazwa_pliku);
		strcpy(edycja, "/tmp/nfs_edycja_");
		strcpy(edycja + 16, nazwa_pliku);

		plik_edycja = open(edycja, O_WRONLY | O_CREAT | O_TRUNC, 0666);
		start_1_arg.tryb = 0;
		result_1 = start_1(&start_1_arg, clnt);
		if (result_1 == (pliczek *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		if(result_1->plik < 0)
        {
			printf("ERROR: Nie mozna otworzyc/utworzyc pliku!\n");
			return;
		}
		pull_1_arg.plik = result_1->plik;
		pull_1_arg.pozycja = 0;
		pull_1_arg.przesun = 0;

		if(result_1->pusty == 0)
		{
			while(1)
            {
				result_2 = pull_1(&pull_1_arg, clnt);
				if(result_2 == (zwroc *) NULL)
                {
					clnt_perror (clnt, "call failed");
				}
				if(result_2->ilosc == -1)
                {
					printf("ERROR: Blad pobierania lub przesuniecia!\n");
					koniec_1_arg = result_1->plik;
					result_4 = koniec_1(&koniec_1_arg, clnt);
					if (result_4 == (int *) NULL)
                    {
						clnt_perror (clnt, "call failed");
					}
					close(plik_edycja);
					exit(-1);
				}
				write(plik_edycja, result_2->dane, result_2->ilosc);
				if(result_2->ilosc < 2048)
				{
				    break;
				}
			}

			koniec_1_arg = result_1->plik;
			result_4 = koniec_1(&koniec_1_arg, clnt);
			if (result_4 == (int *) NULL)
            {
				clnt_perror (clnt, "call failed");
			}
			start_1_arg.tryb = 1;
			result_1 = start_1(&start_1_arg, clnt);
			if (result_1 == (pliczek *) NULL)
            {
				clnt_perror (clnt, "call failed");
			}
		}
		close(plik_edycja);
		strcpy(polecenie, "vi ");
		strcpy(polecenie + 3, edycja);
		system(polecenie);
		plik_edycja = open(edycja, O_RDONLY);

		push_1_arg.plik = result_1->plik;
		while(1)
        {
			wyslane = read(plik_edycja, push_1_arg.dane, 2047);
			push_1_arg.dane[wyslane] = '\0';
			result_3 = push_1(&push_1_arg, clnt);
			if(result_3 == (int *) NULL)
            {
				clnt_perror (clnt, "call failed");
			}
			if(wyslane < 2047)
			{
			    break;
			}
		}
		koniec_1_arg = result_1->plik;
		result_4 = koniec_1(&koniec_1_arg, clnt);
		if(result_4 == (int *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		close(plik_edycja);
	}

	if(strcmp(linia,"download") == 0)   /* Pobieranie pliku */
    {
		strcpy(start_1_arg.nazwa, "/nfs/");
		strcpy(start_1_arg.nazwa+5, nazwa_pliku);
		strcpy(edycja, nazwa_pliku);

		start_1_arg.tryb = 2;
		result_1 = start_1(&start_1_arg, clnt);
		if (result_1 == (pliczek *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		if(result_1->plik < 0)
        {
			printf("ERROR: Brak lub nie mozna otworzyc pliku!\n");
			return;
		}
		plik_edycja = open(edycja, O_WRONLY | O_CREAT | O_TRUNC, 0666);
		pull_1_arg.plik = result_1->plik;
		pull_1_arg.pozycja = 0;
		pull_1_arg.przesun = 0;

		while(1)
        {
			result_2 = pull_1(&pull_1_arg, clnt);
			if(result_2 == (zwroc *) NULL)
            {
				clnt_perror (clnt, "call failed");
			}
			if(result_2->ilosc == -1)
			{
				printf("ERROR: Blad pobierania lub przesuniecia!\n");
				koniec_1_arg = result_1->plik;
				result_4 = koniec_1(&koniec_1_arg, clnt);
				if (result_4 == (int *) NULL)
				{
					clnt_perror (clnt, "call failed");
				}
				close(plik_edycja);
				exit(-1);
			}
			write(plik_edycja, result_2->dane, result_2->ilosc);
			if(result_2->ilosc < 2048)
			{
			    break;
			}
		}
		koniec_1_arg = result_1->plik;
		result_4 = koniec_1(&koniec_1_arg, clnt);
		if (result_4 == (int *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		close(plik_edycja);
	}

	if(strcmp(linia,"upload") == 0) /* Wysylanie pliku */
    {
		strcpy(start_1_arg.nazwa, "/nfs/");
		strcpy(start_1_arg.nazwa+5, nazwa_pliku);
		strcpy(edycja, nazwa_pliku);

		plik_edycja = open(edycja, O_RDONLY);
		if(plik_edycja < 0)
        {
			printf("ERROR: Nie ma takiego pliku pliku lub brak uprawnien!\n");
			return;
		}
		start_1_arg.tryb = 1;
		result_1 = start_1(&start_1_arg, clnt);
		if (result_1 == (pliczek *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		if(result_1->plik < 0)
        {
			printf("ERROR: Nie mozna otworzyc/utworzyc pliku lub bledna komenda!\n");
			return;
		}
		push_1_arg.plik = result_1->plik;
		while(1)
        {
			wyslane = read(plik_edycja, push_1_arg.dane, 2047);
			push_1_arg.dane[wyslane] = '\0';
			result_3 = push_1(&push_1_arg, clnt);
			if (result_3 == (int *) NULL)
            {
				clnt_perror (clnt, "call failed");
			}
			if(wyslane < 2047)
            {
                break;
            }
		}
		koniec_1_arg = result_1->plik;
		result_4 = koniec_1(&koniec_1_arg, clnt);
		if(result_4 == (int *) NULL)
        {
			clnt_perror (clnt, "call failed");
		}
		close(plik_edycja);
	}
	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *operacja;
	if (argc < 2)
    {
        printf ("ERROR: Nieprawidlowa ilosc argumentow\n");
		printf ("Nalezy podac: %s server_host\n", argv[0]);
		exit(-1);
	}
	printf("Serwer NFS wita\n");
	printf("Prosze o wybranie jednej z operacji: 'read' 'open' 'upload' 'download' 'clear' 'close'\n");
	printf("Domyslny edytor: vi\n");
	operacja = argv[1];
	while(1)
    {
		nfs_1 (operacja);
	}
    exit(0);
}
